"use client";
import { Geist, Geist_Mono } from "next/font/google";
import "../styles/fonts.css";

import { Toaster } from "@/components/ui/toaster";
import Footer from "./_components/ui/Footer";
import Header from "./_components/ui/Header";
import { UserProvider } from "./context/userContext";
import "./globals.css";
import { ProductProvider } from "./context/Productcontext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

/* export const metadata = {
  title: "Estee Gold Studio",
  description: "Generated by AtaMLK",
}; */

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased relative`}
      >
        <ProductProvider>
          <UserProvider>
            <Header />
            <main>{children}</main>
            <Toaster />
            <Footer />
          </UserProvider>
        </ProductProvider>
      </body>
    </html>
  );
}
