import { Geist, Geist_Mono } from "next/font/google";
import "../styles/fonts.css";
import LayoutClientWrapper from "./_components/LayoutClientWrapper";
import "./globals.css";
import ToastContainer from "./_components/ui/ToastContainer";
import Providers from "./providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Estee Gold Studio",
  description: "Generated by AtaMLK",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased relative font-inter`}
      >
        {/* ✅ Dynamic header/footer logic moved to client */}

        <LayoutClientWrapper>
          <Providers>{children}</Providers>
          <ToastContainer />
        </LayoutClientWrapper>
      </body>
    </html>
  );
}
