import { Geist, Geist_Mono } from "next/font/google";
import "../styles/fonts.css";
import Footer from "./_components/Footer";
import Header from "./_components/Header";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Estee Gold Studio",
  description: "Generated by AtaMLK",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased relative`}
      >
        <header p>
          <Header />
        </header>
        <main> {children}</main>

        <footer>
          <Footer />
        </footer>
      </body>
    </html>
  );
}
