"use client";

import { useEffect, useMemo, useState } from "react";
import { Plus, Search, Package, Pencil, Power, RefreshCw, X, Upload, Trash2 } from "lucide-react";
import { supabase } from "../../_lib/supabase";
import { useError } from "../../context/errorContext";

const EMPTY = { name: "", branch: "EsteeGold", category: "", description: "", story: "", image_url: "", price_eur: "", price_try: "", price_usd_override: "", price_usd_override_enabled: false, discount_percent: "0", stock: "0", active: true, media: [] };

async function compressImage(file) {
  const bitmap = await createImageBitmap(file), max = 2400, scale = Math.min(1, max / Math.max(bitmap.width, bitmap.height)), canvas = document.createElement("canvas");
  canvas.width = Math.max(1, Math.round(bitmap.width * scale)); canvas.height = Math.max(1, Math.round(bitmap.height * scale));
  const ctx = canvas.getContext("2d", { alpha: true }); ctx.drawImage(bitmap, 0, 0, canvas.width, canvas.height); bitmap.close();
  const blob = await new Promise((resolve) => canvas.toBlob(resolve, "image/webp", 0.92));
  if (!blob) throw new Error(`Could not optimize ${file.name}.`);
  return new File([blob], `${file.name.replace(/\.[^.]+$/, "")}.webp`, { type: "image/webp", lastModified: Date.now() });
}

export default function AdminCatalogPage() {
  const { reportError } = useError();
  const [products, setProducts] = useState([]), [query, setQuery] = useState(""), [branch, setBranch] = useState("all"), [editing, setEditing] = useState(null), [form, setForm] = useState(EMPTY), [mediaFiles, setMediaFiles] = useState([]), [loading, setLoading] = useState(true), [saving, setSaving] = useState(false), [uploading, setUploading] = useState(false), [error, setError] = useState(""), [eurUsdRate, setEurUsdRate] = useState("1.08"), [rateSaving, setRateSaving] = useState(false);
  async function adminRequest(url, options = {}) { const { data: { session } } = await supabase.auth.getSession(); if (!session?.access_token) throw new Error("Please sign in as an administrator."); const response = await fetch(url, { ...options, headers: { ...(options.headers || {}), Authorization: `Bearer ${session.access_token}` } }); let data = {}; try { data = await response.json(); } catch {} if (!response.ok) throw new Error(data.error || `Request failed (${response.status}).`); return data; }
  async function load() { setLoading(true); setError(""); try { const [catalog, pricing] = await Promise.all([adminRequest("/api/admin/catalog", { cache: "no-store" }), adminRequest("/api/admin/pricing", { cache: "no-store" })]); setProducts(catalog.products || []); setEurUsdRate(String(pricing.settings?.eur_usd_rate || 1.08)); } catch (e) { setError(reportError(e, "Could not load the catalog.")); } finally { setLoading(false); } }
  useEffect(() => { load(); }, []);
  const visible = useMemo(() => products.filter((p) => (branch === "all" || p.branch === branch) && `${p.name} ${p.category || ""}`.toLowerCase().includes(query.toLowerCase())), [products, query, branch]);
  function openCreate() { setEditing("new"); setForm(EMPTY); setMediaFiles([]); setError(""); }
  function openEdit(product) { setEditing(product.id); setForm({ ...EMPTY, ...product, price_eur: product.price_eur ?? product.price ?? "", price_try: product.price_try ?? "", price_usd_override: product.price_usd_override ?? "", discount_percent: product.discount_percent ?? 0, stock: product.stock ?? 0, media: product.media || [] }); setMediaFiles([]); setError(""); }
  async function uploadMedia(productId, files) { if (!files.length) return; setUploading(true); try { const optimized = []; for (const file of files) optimized.push(file.type.startsWith("image/") ? await compressImage(file) : file); const body = new FormData(); body.append("productId", productId); optimized.forEach((file) => body.append("files", file, file.name)); await adminRequest("/api/admin/catalog/media", { method: "POST", body }); } finally { setUploading(false); } }
  async function removeMedia(id) { try { await adminRequest("/api/admin/catalog/media", { method: "DELETE", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id }) }); await load(); if (editing !== "new") setForm((v) => ({ ...v, media: v.media.filter((item) => item.id !== id) })); } catch (e) { setError(reportError(e, "Could not delete media.")); } }
  async function save(event) { event.preventDefault(); setSaving(true); setError(""); try { const data = await adminRequest("/api/admin/catalog", { method: editing === "new" ? "POST" : "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...(editing !== "new" ? { id: editing } : {}), ...form, price_eur: Number(form.price_eur), price_try: form.price_try === "" ? null : Number(form.price_try), price_usd_override: form.price_usd_override === "" ? null : Number(form.price_usd_override), discount_percent: Number(form.discount_percent || 0), stock: Number(form.stock || 0) }) }); const productId = data.product?.id || editing; if (productId && mediaFiles.length) await uploadMedia(productId, mediaFiles); setEditing(null); setMediaFiles([]); await load(); } catch (e) { setError(reportError(e, "Could not save this product.")); } finally { setSaving(false); } }
  async function saveRate(event) { event.preventDefault(); setRateSaving(true); setError(""); try { await adminRequest("/api/admin/pricing", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ eur_usd_rate: Number(eurUsdRate) }) }); await load(); } catch (e) { setError(reportError(e, "Could not save EUR/USD rate.")); } finally { setRateSaving(false); } }
  async function toggle(product) { try { await adminRequest("/api/admin/catalog", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id: product.id, active: !product.active }) }); await load(); } catch (e) { setError(reportError(e, "Could not change product visibility.")); } }

  return <main className="min-h-screen bg-[var(--paper)] px-5 pb-24 pt-28 md:px-10"><div className="mx-auto max-w-7xl">
    <header className="flex flex-col gap-6 border-b border-black/10 pb-8 md:flex-row md:items-end md:justify-between"><div><p className="text-[9px] uppercase tracking-[0.3em] text-black/40">EsteeHouse / Admin</p><h1 className="mt-4 font-serif text-6xl tracking-[-0.06em] md:text-8xl">Catalog.</h1><p className="mt-4 max-w-xl text-sm leading-6 text-black/45">Products, regional prices, stories and rich media.</p></div><button onClick={openCreate} className="inline-flex items-center justify-center gap-2 rounded-full bg-black px-6 py-3 text-[9px] uppercase tracking-[0.22em] text-white"><Plus size={14}/> Add product</button></header>
    <section className="my-6 grid gap-4 rounded-2xl border border-black/10 p-5 md:grid-cols-[1fr_auto] md:items-center"><div><p className="text-[8px] uppercase tracking-[.22em] text-black/40">Global FX</p><p className="mt-2 text-sm">1 EUR = {Number(eurUsdRate || 0).toFixed(4)} USD</p><p className="mt-1 text-xs text-black/40">USD prices follow this rate unless a product has a manual USD override.</p></div><form onSubmit={saveRate} className="flex items-center gap-3"><input value={eurUsdRate} onChange={(e) => setEurUsdRate(e.target.value)} type="number" min="0.000001" step="0.0001" className="w-32 border-b border-black/20 bg-transparent py-2 text-sm outline-none"/><button disabled={rateSaving} className="rounded-full bg-black px-5 py-3 text-[8px] uppercase tracking-[.2em] text-white">{rateSaving ? "Saving…" : "Save rate"}</button></form></section>
    <section className="flex flex-col gap-4 border-b border-black/10 py-5 md:flex-row md:items-center md:justify-between"><div className="flex flex-wrap gap-2">{["all", "EsteeGold", "EsteeBags"].map((item) => <button key={item} onClick={() => setBranch(item)} className={`rounded-full border px-4 py-2 text-[8px] uppercase tracking-[0.2em] ${branch === item ? "bg-black text-white" : "border-black/15"}`}>{item === "all" ? "All" : item}</button>)}</div><label className="flex items-center gap-2 border-b border-black/15 pb-2 text-sm"><Search size={14} className="text-black/35"/><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search products" className="bg-transparent outline-none"/></label></section>
    {error && <div role="alert" className="mt-5 rounded-xl border border-red-900/10 bg-red-50 px-4 py-3 text-sm text-red-900">{error}</div>}
    <section className="py-8">{loading ? <div className="flex items-center gap-3 py-20 text-sm text-black/45"><RefreshCw size={15} className="animate-spin"/> Loading catalog…</div> : visible.length === 0 ? <div className="grid min-h-[35vh] place-items-center text-center"><div><Package size={28} className="mx-auto text-black/20"/><p className="mt-4 font-serif text-3xl">No products found.</p></div></div> : <div className="overflow-x-auto rounded-2xl border border-black/10"><table className="w-full min-w-[1050px] text-left"><thead className="border-b border-black/10 bg-black/[.025] text-[8px] uppercase tracking-[.2em] text-black/40"><tr><th className="px-5 py-4">Product</th><th>Branch</th><th>Category</th><th>EUR</th><th>TRY</th><th>USD</th><th>Stock</th><th>Status</th><th className="px-5">Actions</th></tr></thead><tbody>{visible.map((p) => { const eur = Number(p.price_eur ?? p.price ?? 0), usd = p.price_usd_override_enabled && p.price_usd_override != null ? Number(p.price_usd_override) : eur * Number(eurUsdRate || 1.08); return <tr key={p.id} className="border-b border-black/5 last:border-0"><td className="px-5 py-4"><div className="font-serif text-xl">{p.name}</div><div className="mt-1 max-w-xs truncate text-xs text-black/35">{p.description || "No description"}</div><div className="mt-1 text-[8px] uppercase tracking-[.15em] text-black/30">{p.media?.length || 0} media</div></td><td className="text-xs">{p.branch}</td><td className="text-xs">{p.category || "—"}</td><td className="text-sm">€{eur.toFixed(2)}</td><td className="text-sm">{p.price_try ? `₺${Number(p.price_try).toFixed(2)}` : "—"}</td><td className="text-sm">${usd.toFixed(2)}</td><td className="text-sm">{p.stock ?? 0}</td><td><span className={`rounded-full px-3 py-1 text-[8px] uppercase tracking-[.15em] ${p.active ? "bg-black text-white" : "bg-black/5 text-black/40"}`}>{p.active ? "Active" : "Hidden"}</span></td><td className="px-5"><div className="flex gap-2"><button title="Edit" onClick={() => openEdit(p)} className="rounded-full border border-black/10 p-2"><Pencil size={13}/></button><button title={p.active ? "Hide" : "Activate"} onClick={() => toggle(p)} className="rounded-full border border-black/10 p-2"><Power size={13}/></button></div></td></tr>; })}</tbody></table></div>}</section>
  </div>{editing && <div className="fixed inset-0 z-50 grid place-items-center bg-black/45 p-5" onMouseDown={(e) => e.target === e.currentTarget && setEditing(null)}><form onSubmit={save} className="max-h-[92vh] w-full max-w-3xl overflow-y-auto rounded-[2rem] bg-[var(--paper)] p-7 md:p-10"><div className="flex items-start justify-between"><div><p className="text-[8px] uppercase tracking-[.25em] text-black/40">{editing === "new" ? "New product" : "Edit product"}</p><h2 className="mt-3 font-serif text-4xl">Product details</h2></div><button type="button" onClick={() => setEditing(null)} className="text-xl text-black/40"><X size={18}/></button></div>
    <div className="mt-8 grid gap-5 sm:grid-cols-2">{[["name","Name","text"],["category","Category","text"],["image_url","Legacy / fallback image URL","url"],["price_eur","Price (€)","number"],["price_try","Turkey price (₺)","number"],["price_usd_override","Manual USD price","number"],["discount_percent","Discount %","number"],["stock","Stock","number"]].map(([key,label,type]) => <label key={key} className="text-[8px] uppercase tracking-[.18em] text-black/45">{label}<input required={key === "name" || key === "price_eur"} type={type} min={type === "number" ? "0" : undefined} max={key === "discount_percent" ? "100" : undefined} step={key === "price_eur" || key === "price_try" || key === "price_usd_override" ? "0.01" : key === "discount_percent" ? "1" : undefined} value={form[key] ?? ""} onChange={(e) => setForm((v) => ({ ...v, [key]: e.target.value }))} className="mt-2 w-full border-b border-black/15 bg-transparent py-3 text-sm normal-case tracking-normal outline-none focus:border-black"/></label>)}<label className="text-[8px] uppercase tracking-[.18em] text-black/45">Branch<select value={form.branch} onChange={(e) => setForm((v) => ({ ...v, branch: e.target.value }))} className="mt-2 w-full border-b border-black/15 bg-transparent py-3 text-sm normal-case tracking-normal outline-none"><option>EsteeGold</option><option>EsteeBags</option></select></label><label className="flex items-center gap-3 text-sm"><input type="checkbox" checked={!!form.price_usd_override_enabled} onChange={(e) => setForm((v) => ({ ...v, price_usd_override_enabled: e.target.checked }))}/> Use manual USD price</label><label className="flex items-center gap-3 text-sm"><input type="checkbox" checked={!!form.active} onChange={(e) => setForm((v) => ({ ...v, active: e.target.checked }))}/> Active in storefront</label><label className="text-[8px] uppercase tracking-[.18em] text-black/45 sm:col-span-2">Description<textarea value={form.description} onChange={(e) => setForm((v) => ({ ...v, description: e.target.value }))} rows={3} className="mt-2 w-full rounded-xl border border-black/10 bg-transparent p-3 text-sm normal-case tracking-normal outline-none focus:border-black"/></label><label className="text-[8px] uppercase tracking-[.18em] text-black/45 sm:col-span-2">Product story<textarea value={form.story} onChange={(e) => setForm((v) => ({ ...v, story: e.target.value }))} rows={4} placeholder="Write this like the brand owner is speaking." className="mt-2 w-full rounded-xl border border-black/10 bg-transparent p-3 text-sm normal-case tracking-normal outline-none focus:border-black"/></label></div>
    <section className="mt-8 rounded-2xl border border-black/10 p-5"><div className="flex items-center justify-between gap-4"><div><p className="text-[8px] uppercase tracking-[.22em] text-black/40">Product media</p><p className="mt-2 text-xs text-black/45">Add multiple photos and optional video. Photos are automatically resized and converted to high-quality WebP before upload.</p></div><Upload size={17} className="text-black/35"/></div><input type="file" accept="image/*,video/*" multiple onChange={(e) => setMediaFiles(Array.from(e.target.files || []))} className="mt-5 block w-full text-xs"/>{mediaFiles.length > 0 && <p className="mt-3 text-xs text-black/45">{mediaFiles.length} new file(s) ready. Images will be optimized automatically.</p>}{form.media?.length > 0 && <div className="mt-5 grid grid-cols-3 gap-3">{form.media.map((item) => <div key={item.id} className="relative overflow-hidden rounded-xl border border-black/10 bg-black/[.03]">{item.kind === "video" ? <video src={item.url} className="aspect-square w-full object-cover" muted/> : <img src={item.url} alt="" className="aspect-square w-full object-cover"/>}<button type="button" onClick={() => removeMedia(item.id)} className="absolute right-2 top-2 rounded-full bg-white/90 p-2" title="Delete media"><Trash2 size={12}/></button></div>)}</div>}</section><button disabled={saving || uploading} className="mt-8 w-full rounded-full bg-black px-6 py-4 text-[9px] uppercase tracking-[.25em] text-white disabled:opacity-40">{uploading ? "Optimizing & uploading media…" : saving ? "Saving…" : "Save product"}</button>
  </form></div>}</main>;
}
