-- Product storytelling is part of the storefront content, not generated at render time.
alter table public.commerce_products add column if not exists story text not null default '';

update public.commerce_products
set story = case id
  when '1' then 'I wanted the Essential Ring to be the piece you stop noticing because it already belongs on your hand. The profile stays clean, but the finish keeps enough life in the metal to avoid feeling anonymous.'
  when '2' then 'This set started with the idea that pieces should work together without looking like they were bought together. The layers are close enough to feel intentional and loose enough to make them your own.'
  when '3' then 'I kept coming back to the balance between a strong shape and a light feel. These earrings have presence from across the room, but they still move easily when you wear them.'
  when '4' then 'The Hand Combination is built for people who like to wear more than one piece but still want the whole hand to feel considered. I left small differences between the elements so it does not look factory-perfect.'
  when '5' then 'A good everyday earring should not need an occasion. This pair is deliberately uncomplicated: a little shine, a comfortable weight and a shape that works when the rest of the outfit changes.'
  when '6' then 'The Everyday Bracelet is about the quiet details you notice after wearing it for a while. The surface catches differently as the wrist moves, which is exactly what I wanted.'
  else story
end
where id in ('1','2','3','4','5','6');

insert into public.commerce_products
  (id,name,branch,category,description,image_url,price,discount_percent,active,story)
values
('demo-01','After Rain Ring','EsteeGold','Rings','A slim silver ring with a softened edge. It catches light quietly rather than asking for it.','https://loremflickr.com/1200/1500/jewelry?lock=11',78,0,true,'I kept this one deliberately simple. The idea was to make a ring that feels familiar from the first day, with enough weight to stay present without becoming the whole outfit.'),
('demo-02','Low Tide Band','EsteeGold','Rings','A rounded band with a hand-finished surface and a slightly irregular profile.','https://loremflickr.com/1200/1500/jewelry?lock=12',92,0,true,'The first version was too perfect. I took it back to the bench and softened the surface until it looked like something that had already lived a little.'),
('demo-03','Quiet Arc Ring','EsteeGold','Rings','An open silver form designed to sit lightly across the finger.','https://loremflickr.com/1200/1500/jewelry?lock=13',84,5,true,'I wanted the negative space to do as much work as the metal. From some angles you barely notice it; from others, that small opening becomes the whole point.'),
('demo-04','Olive Line Cuff','EsteeGold','Bracelets','A clean cuff with a warm olive-toned detail and a hand-brushed finish.','https://loremflickr.com/1200/1500/jewelry?lock=14',118,0,true,'The olive detail came late. It was the small contrast the piece needed, something that would make silver feel less formal and more personal.'),
('demo-05','Sunday Chain','EsteeGold','Necklaces','A fine chain necklace made for everyday wear and easy layering.','https://loremflickr.com/1200/1500/jewelry?lock=15',105,0,true,'This is the necklace I imagined reaching for without thinking. It works with a T-shirt, a shirt, a dress, and the days when you simply want one good thing around your neck.'),
('demo-06','Small Hours Pendant','EsteeGold','Necklaces','A compact pendant with a softly reflective face and a restrained silhouette.','https://loremflickr.com/1200/1500/jewelry?lock=16',112,0,true,'The shape came from looking at old keys and worn coins. Nothing precious on its own, but full of the marks that make an object worth keeping.'),
('demo-07','First Light Hoops','EsteeGold','Earrings','Small hoop earrings with a polished outer edge and a softer inner finish.','https://loremflickr.com/1200/1500/jewelry?lock=17',69,0,true,'I wanted a hoop that could stay on from morning to late dinner. Small enough to disappear when you stop thinking about it, strong enough to finish a look.'),
('demo-08','Stone Drop Earrings','EsteeGold','Earrings','Minimal drop earrings balancing a small stone with a clean silver line.','https://loremflickr.com/1200/1500/jewelry?lock=18',88,10,true,'The stone is intentionally understated. It gives the eye somewhere to stop, while the silver keeps the piece from becoming too dressed up.'),
('demo-09','Palm Shadow Bracelet','EsteeGold','Bracelets','A narrow bracelet with a darkened recess that brings out the hand-finished texture.','https://loremflickr.com/1200/1500/jewelry?lock=19',96,0,true,'I like the way shadows change metal. Instead of polishing everything away, I left a darker line in the recess so the shape stays visible from across the room.'),
('demo-10','Second Skin Chain','EsteeGold','Necklaces','A light everyday chain with a close, comfortable fall at the collarbone.','https://loremflickr.com/1200/1500/jewelry?lock=20',89,0,true,'This one is about restraint. It is there when you need a little detail, but it never competes with the person wearing it.'),
('demo-11','Night Market Ring','EsteeGold','Rings','A heavier silver ring with a low profile and a satin finish.','https://loremflickr.com/1200/1500/jewelry?lock=21',124,0,true,'The name came from late walks through city streets. I wanted the finish to feel a little darker, like metal under shop lights after sunset.'),
('demo-12','Folded Line Pendant','EsteeGold','Necklaces','A geometric pendant built from one continuous folded line.','https://loremflickr.com/1200/1500/jewelry?lock=22',132,0,true,'There is no hidden trick here. One line, one fold, one small decision about proportion. That is enough when the shape is right.'),
('demo-13','Soft Edge Bangle','EsteeGold','Bracelets','A rounded bangle with a satin surface that becomes brighter along the edges.','https://loremflickr.com/1200/1500/jewelry?lock=23',138,0,true,'The edge is where this piece lives. I spent more time there than anywhere else because that is the part you feel when you move your wrist.'),
('demo-14','Threaded Hoops','EsteeGold','Earrings','Slim hoops with a fine textured line wrapped around the outer curve.','https://loremflickr.com/1200/1500/jewelry?lock=24',76,0,true,'I wanted the texture to be discovered, not announced. From far away they read as simple hoops; up close, the surface starts to tell its own story.'),
('demo-15','Dune Bracelet','EsteeGold','Bracelets','A sculptural bracelet with gentle rises and a brushed silver finish.','https://loremflickr.com/1200/1500/jewelry?lock=25',146,5,true,'The name is about the surface, not the destination. I was chasing the quiet movement you see in sand after the wind has passed.'),
('demo-16','Everyday Signet','EsteeGold','Rings','A compact signet with a broad face, softened corners and a hand-worked finish.','https://loremflickr.com/1200/1500/jewelry?lock=26',128,0,true,'I did not want a signet that looked inherited from another era. The proportions are modern, but the little marks are deliberately human.'),
('demo-17','Open Circle Pendant','EsteeGold','Necklaces','An open circular pendant with a slightly uneven hand-shaped profile.','https://loremflickr.com/1200/1500/jewelry?lock=27',99,0,true,'A perfect circle can feel distant. I opened it up and let the hand finish show, so the piece feels closer to the person who made it.'),
('demo-18','Late Summer Studs','EsteeGold','Earrings','Small silver studs with a warm polished face and softly irregular edges.','https://loremflickr.com/1200/1500/jewelry?lock=28',62,0,true,'These came from a very simple wish: earrings that look good with nothing else. No ceremony, no occasion, just a pair you keep reaching for.'),
('demo-19','Found Object Chain','EsteeGold','Necklaces','A textured chain finished with a small found-object-inspired charm.','https://loremflickr.com/1200/1500/jewelry?lock=29',119,0,true,'The charm started as a sketch of something found on a workbench. I kept the marks from that first drawing because they gave the final piece its character.'),
('demo-20','Last Light Cuff','EsteeGold','Bracelets','A wide cuff with a darkened centre and a brighter hand-polished edge.','https://loremflickr.com/1200/1500/jewelry?lock=30',158,0,true,'I wanted the last piece in this small set to feel like evening light on metal: darker in the middle, brighter where the surface turns toward you.')
on conflict (id) do update set name=excluded.name,branch=excluded.branch,category=excluded.category,description=excluded.description,image_url=excluded.image_url,price=excluded.price,discount_percent=excluded.discount_percent,active=excluded.active,story=excluded.story,updated_at=now();
